spring:

  main:
    banner-mode: "off"
    log-startup-info: "false"
  
  application:
    name: "Movies Battle API"

  datasource:
    url: jdbc:h2:file:./resources/data/movies-battle-db
    username: tnas
    password: tnasAdmin
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect